[http://metrics_backfill]
disabled = 1
host = localhost
index = itsi_im_metrics
indexes = itsi_im_metrics
token = CHANGE_ME_METRICS_HEC_TOKEN

[http://mysql_backfill]
disabled = 1
host = localhost
index = mysql
indexes = mysql
token = CHANGE_ME_MYSQL_HEC_TOKEN
