[eventstorm_hosts]
filename = eventstorm_hosts.csv
case_sensitive_match = false

[edu_dc1_hosts]
filename = edu_dc1_hosts.csv
case_sensitive_match = false

[edu_dc2_hosts]
filename = edu_dc2_hosts.csv
case_sensitive_match = false

[slg_dc1_hosts]
filename = slg_dc1_hosts.csv
case_sensitive_match = false

[slg_dc2_hosts]
filename = slg_dc2_hosts.csv
case_sensitive_match = false

[edu_dc1_set_index_host]
REGEX = "index_host"\s*:\s*"([^"]+)"
FORMAT = host::$1
DEST_KEY = MetaData:Host
WRITE_META = true

[edu_dc1_log_to_metrics]
TYPE = metric_schema
METRIC-SCHEMA-MEASURES = metric_name:processmon.cpu.percent, metric_name:cpu.interrupt, metric_name:cpu.nice, metric_name:cpu.softriq, metric_name:cpu.steal, metric_name:cpu.system, metric_name:cpu.user, metric_name:cpu.wait, metric_name:cpu.idle, metric_name:df.reserved, metric_name:df.used, metric_name:df.free, metric_name:disk.io_time.io_time, metric_name:disk.io_time.weighted_io_time, metric_name:disk.merged.read, metric_name:disk.merged.write, metric_name:disk.octets.read, metric_name:disk.octets.write, metric_name:disk.ops.read, metric_name:disk.ops.write, metric_name:disk.time.read, metric_name:disk.time.write, metric_name:memory.buffered, metric_name:memory.cached, metric_name:memory.slab_recl, metric_name:memory.slab_unrecl, metric_name:memory.used, metric_name:memory.free, metric_name:interface.dropped.rx, metric_name:interface.dropped.tx, metric_name:interface.errors.rx, metric_name:interface.errors.tx, metric_name:interface.octets.rx, metric_name:interface.octets.tx, metric_name:interface.packets.rx, metric_name:interface.packets.tx, metric_name:Processor.%_Idle_Time, metric_name:Memory.%_Committed_Bytes_In_Use, metric_name:LogicalDisk.%_Free_Space, metric_name:Avg._Disk_Bytes/Read, metric_name:Avg._Disk_Bytes/Write, metric_name:Network_Interface.Bytes_Received/sec, metric_name:Network_Interface.Bytes_Sent/sec
METRIC-SCHEMA-DIMENSIONS = role, ip, entity_type, os_version, process_name, os, instance

[rum_log_to_metrics]
TYPE = metric_schema
METRIC-SCHEMA-MEASURES = metric_name:rum.page_view.count, metric_name:rum.client_error.count, metric_name:rum.page_view.time.ns.p75, metric_name:rum.resource_request.count, metric_name:rum.webvitals_lcp.time.ns.p75, metric_name:rum.resource_request.time.ns.p75, metric_name:rum.webvitals_fid.time.ns.p75, metric_name:rum.webvitals_cls.score.p75
METRIC-SCHEMA-DIMENSIONS = app, computationId, country, sf_environment, sf_node_type, sf_operation, sf_organizationID, sf_product, sf_realm, sf_resolutionMs, sf_ua_browsername, sf_ua_osname, entity_type

[apm_log_to_metrics]
TYPE = metric_schema
METRIC-SCHEMA-MEASURES = metric_name:service.request.count, metric_name:service.request.ns.median, metric_name:service.request.ns.p99
METRIC-SCHEMA-DIMENSIONS = computationId, sf_environment, sf_organizationID, sf_realm, sf_resolutionMs, sf_service, sf_streamLabel, sf_error
